### ISSUE TITLE
HmacHhelper test failing

### ISSUE THREAD

**Issue by marcodejongh** [p-j/meteor-crypto-sha256#2]
See my build log for more info:
https://travis-ci.org/marcodejongh/meteor-crypto-sha256/builds/42325242

```
S: tinytest - MeteorCryptoSHA256 - HmacHelper : !!!!!!!!! FAIL !!!!!!!!!!!
TypeError: Cannot read property 'init' of undefined
    at Object.HmacSHA256 (packages/jparker:crypto-core/lib/core.js:701)
    at Package (packages/local-test:meteor-crypto-sha256/tests/tests.js:101)
    at null.func (packages/tinytest/tinytest.js:594)
    at packages/tinytest/tinytest.js:372
    at _.extend.withValue (packages/meteor/dynamics_nodejs.js:56)
    at packages/meteor/timers.js:6
    at runWithEnvironment (packages/meteor/dynamics_nodejs.js:108)
```

**Comment by p-j** [comment]
Hi,

It is indeed failing. Thanks for catching it.

It's because the [`jparker:crypto-hmac`](https://github.com/p-j/meteor-crypto-hmac) is required for that last test to pass. 
I should either make it a dependency for the test, or, add a package detection to decide whether I should run this test or not.

**Comment by marcodejongh** [comment]
Porbaply include it for the package then in onUse

**Comment by p-j** [comment]
It's [fixed now](https://github.com/p-j/meteor-crypto-sha256/commit/1b84799a170c31b91c2788daa7599eca59caa28c) thanks again for reporting this issue.
